<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>MedSched Reports</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a3a5c; background: #fff; padding: 24px; }

        .report-header { text-align: center; margin-bottom: 6px; }
        .report-title { font-size: 22px; font-weight: 800; color: #1a3a5c; }
        .report-meta { font-size: 10px; color: #5a7a9c; margin-top: 4px; }

        .section-title { font-size: 14px; font-weight: 800; color: #1a3a5c; margin-bottom: 8px; margin-top: 20px; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        thead tr { background: #1976d2; color: white; }
        thead th { padding: 8px 6px; text-align: left; font-size: 10px; }
        tbody tr:nth-child(even) { background: #f0f4ff; }
        tbody td { padding: 7px 6px; font-size: 10px; border-bottom: 1px solid #ddd; }

        .badge { padding: 2px 8px; border-radius: 10px; font-size: 9px; font-weight: 700; display: inline-block; }
        .td-center { text-align: center; }
        .td-status { text-align: center; }
        .badge-done      { background: #c8e6c9; color: #256029; }
        .badge-cancelled { background: #ffcdd2; color: #b71c1c; }
        .badge-pending   { background: #fff9c4; color: #856404; }
        .badge-confirmed { background: #bbdefb; color: #0d47a1; }

        .divider { border: none; border-top: 1.5px solid #d0e8f8; margin: 10px 0 20px 0; }
    </style>
</head>
<body>

    {{-- HEADER --}}
    <div class="report-header">
        <div class="report-title">MedSched Reports</div>
        <div class="report-meta">
            Generated by: {{ Auth::user()->fullname ?? 'Admin' }} &nbsp;|&nbsp;
            {{ now()->timezone('Asia/Manila')->format('F d, Y h:i A') }}
        </div>
    </div>

    <hr class="divider">

    {{-- STAT CARDS --}}
    <table style="margin-bottom: 20px;">
        <tr>
            <td style="width:20%; background:#b2dfdb; border-radius:8px; text-align:center; padding:12px; font-weight:800;">
                <div style="font-size:9px; margin-bottom:4px;">Total Appointments</div>
                <div style="font-size:20px;">{{ $totalAppointments }}</div>
            </td>
            <td style="width:4%;"></td>
            <td style="width:20%; background:#b2dfdb; border-radius:8px; text-align:center; padding:12px; font-weight:800;">
                <div style="font-size:9px; margin-bottom:4px;">Total Patients</div>
                <div style="font-size:20px;">{{ $totalPatients }}</div>
            </td>
            <td style="width:4%;"></td>
            <td style="width:20%; background:#b2dfdb; border-radius:8px; text-align:center; padding:12px; font-weight:800;">
                <div style="font-size:9px; margin-bottom:4px;">Completed</div>
                <div style="font-size:20px;">{{ $done }}</div>
            </td>
            <td style="width:4%;"></td>
            <td style="width:20%; background:#b2dfdb; border-radius:8px; text-align:center; padding:12px; font-weight:800;">
                <div style="font-size:9px; margin-bottom:4px;">Pending</div>
                <div style="font-size:20px;">{{ $pending }}</div>
            </td>
            <td style="width:4%;"></td>
            <td style="width:20%; background:#b2dfdb; border-radius:8px; text-align:center; padding:12px; font-weight:800;">
                <div style="font-size:9px; margin-bottom:4px;">Cancelled</div>
                <div style="font-size:20px;">{{ $cancelled }}</div>
            </td>
        </tr>
    </table>

    {{-- APPOINTMENTS TABLE --}}
    <div class="section-title">Appointments Summary</div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Patient Name</th>
                <th>Doctor</th>
                <th>Date</th>
                <th>Time</th>
                <th style="text-align:center;">Status</th>
                <th>Reason</th>
            </tr>
        </thead>
        <tbody>
            @forelse($appointments as $index => $appt)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $appt->patient->name ?? 'N/A' }}</td>
                <td>Dr. {{ $appt->doctor->name ?? 'N/A' }}</td>
                <td>{{ \Carbon\Carbon::parse($appt->appointment_date)->format('M d, Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($appt->appointment_time)->format('h:i A') }}</td>
                <td class="td-status">
                    @php $s = strtolower($appt->status); @endphp
                    @if($s === 'done' || $s === 'completed')
                        <span class="badge badge-done">Done</span>
                    @elseif($s === 'cancelled')
                        <span class="badge badge-cancelled">Cancelled</span>
                    @elseif($s === 'pending')
                        <span class="badge badge-pending">Pending</span>
                    @else
                        <span class="badge badge-confirmed">{{ ucfirst($appt->status) }}</span>
                    @endif
                </td>
                <td>{{ $appt->reason ?? '—' }}</td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center; color:#888; padding:16px;">No appointments found.</td></tr>
            @endforelse
        </tbody>
    </table>

    {{-- PATIENTS TABLE --}}
    <div class="section-title">Patient List</div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Patient Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th style="text-align:center;">Total Appointments</th>
                <th style="text-align:center;">Completed</th>
                <th style="text-align:center;">Cancelled</th>
            </tr>
        </thead> 
        <tbody>
            @forelse($patients as $index => $patient)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $patient->name }}</td>
                <td>{{ $patient->user->email ?? '—' }}</td>
                <td>{{ $patient->phone ?? '—' }}</td>
                <td class="td-center">{{ $patient->appointments->count() }}</td>
                <td class="td-center">{{ $patient->appointments->where('status','done')->count() }}</td>
                <td class="td-center">{{ $patient->appointments->where('status','cancelled')->count() }}</td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center; color:#888; padding:16px;">No patients found.</td></tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>